/**
 * Original bilingual card text for the built-in `bunker-party-v1` pack.
 *
 * Counts follow the 3.3 reference composition: 50 Profession, 32 Biology,
 * 32 Health, 32 Hobby, 32 Baggage, 50 Fact, 32 Special Condition,
 * 20 Catastrophe, 30 Bunker, 21 Threat.
 */

/** `[uk, en]` for a title, followed by `[uk, en]` for its detail line. */
export type CardEntry = readonly [
  titleUk: string,
  titleEn: string,
  detailUk: string,
  detailEn: string,
];

export const PROFESSION_CARDS: readonly CardEntry[] = [
  [
    "Хірург-травматолог",
    "Trauma surgeon",
    "12 років операційної; оперує без апаратури, якщо є світло й спирт.",
    "12 years in the OR; can operate with light and alcohol alone.",
  ],
  [
    "Медсестра-анестезистка",
    "Nurse anaesthetist",
    "Веде наркоз і реанімацію, ставить крапельниці наосліп.",
    "Runs anaesthesia and resuscitation, finds a vein blind.",
  ],
  [
    "Парамедик",
    "Paramedic",
    "Сортує поранених і зупиняє кровотечу за 20 секунд.",
    "Triages casualties and stops a bleed in 20 seconds.",
  ],
  [
    "Ветеринар",
    "Veterinarian",
    "Лікує худобу, приймає отелення, знає дози ліків для людей.",
    "Treats livestock, delivers calves, knows human dosages too.",
  ],
  [
    "Фармацевт",
    "Pharmacist",
    "Синтезує прості ліки й антисептики з побутової хімії.",
    "Compounds simple drugs and antiseptics from household stock.",
  ],
  [
    "Інженер-механік",
    "Mechanical engineer",
    "Проєктує й лагодить насоси, приводи, вентиляцію.",
    "Designs and repairs pumps, drives and ventilation.",
  ],
  [
    "Електрик-високовольтник",
    "High-voltage electrician",
    "Заводить генератор і розводить мережу бункера.",
    "Starts a generator and wires a shelter grid.",
  ],
  [
    "Сантехнік",
    "Plumber",
    "Тримає воду й каналізацію у робочому стані.",
    "Keeps water and sewage running.",
  ],
  [
    "Зварювальник",
    "Welder",
    "Варить сталь і чавун, ремонтує герметичні двері.",
    "Welds steel and cast iron, repairs pressure doors.",
  ],
  [
    "Тесля",
    "Carpenter",
    "Ставить кроквяні конструкції та нари з підручного лісу.",
    "Frames roofs and bunks from whatever timber is at hand.",
  ],
  [
    "Муляр",
    "Bricklayer",
    "Мурує стіни, кладе печі, замішує розчин на око.",
    "Lays walls and stoves, mixes mortar by eye.",
  ],
  [
    "Агроном",
    "Agronomist",
    "Планує сівозміну й рятує врожай від хвороб.",
    "Plans crop rotation and saves a harvest from blight.",
  ],
  [
    "Фермер",
    "Farmer",
    "Тримав 30 гектарів і стадо; орав, сіяв, різав.",
    "Ran 30 hectares and a herd; ploughed, sowed, slaughtered.",
  ],
  [
    "Пасічник",
    "Beekeeper",
    "Дає мед, віск і запилення для теплиць.",
    "Provides honey, wax and pollination for greenhouses.",
  ],
  [
    "Рибалка",
    "Fisher",
    "Ставить сіті й читає воду; коптить улов.",
    "Sets nets, reads water, smokes the catch.",
  ],
  [
    "Мисливець-промисловик",
    "Subsistence hunter",
    "Тропить звіра, білує тушу, ставить пастки.",
    "Tracks game, butchers a carcass, sets snares.",
  ],
  [
    "Кухар громадського харчування",
    "Institutional cook",
    "Готує на 200 осіб із мінімуму продуктів.",
    "Feeds 200 people from a minimal pantry.",
  ],
  [
    "Пекар",
    "Baker",
    "Веде закваску й пече в саморобній печі.",
    "Keeps a sourdough starter and bakes in an improvised oven.",
  ],
  [
    "Кравець",
    "Tailor",
    "Шиє й перешиває одяг, лагодить намети.",
    "Sews and alters clothing, patches tents.",
  ],
  [
    "Швець",
    "Shoemaker",
    "Робить і ремонтує взуття зі шкіри та гуми.",
    "Makes and repairs footwear from leather and rubber.",
  ],
  [
    "Хімік-технолог",
    "Process chemist",
    "Робить мило, хлор, паливні суміші.",
    "Produces soap, chlorine and fuel mixes.",
  ],
  [
    "Мікробіолог",
    "Microbiologist",
    "Визначає збудника й ставить карантин.",
    "Identifies a pathogen and sets a quarantine.",
  ],
  [
    "Геолог",
    "Geologist",
    "Шукає воду й породу, оцінює стійкість ґрунту.",
    "Finds water and rock, judges ground stability.",
  ],
  [
    "Метеоролог",
    "Meteorologist",
    "Прогнозує погоду й переніс радіоактивних опадів.",
    "Forecasts weather and fallout drift.",
  ],
  [
    "Інженер-ядерник",
    "Nuclear engineer",
    "Читає дозиметрію й рахує безпечний час на поверхні.",
    "Reads dosimetry and computes safe time outside.",
  ],
  [
    "Програміст",
    "Software engineer",
    "Оживляє стару автоматику та облік ресурсів.",
    "Revives legacy automation and resource accounting.",
  ],
  [
    "Системний адміністратор",
    "Systems administrator",
    "Тримає мережу, живлення й резервні копії.",
    "Keeps the network, power and backups alive.",
  ],
  [
    "Радіоінженер",
    "Radio engineer",
    "Будує антену й ловить далекі передачі.",
    "Builds an antenna and picks up distant broadcasts.",
  ],
  [
    "Оператор безпілотників",
    "Drone operator",
    "Веде розвідку місцевості без ризику для людей.",
    "Scouts terrain without risking anyone.",
  ],
  [
    "Пілот цивільної авіації",
    "Airline pilot",
    "Навігація, метео, холодна голова в аварії.",
    "Navigation, weather, a cold head in an emergency.",
  ],
  [
    "Машиніст локомотива",
    "Train driver",
    "Знає колію, депо й ручне гальмування составу.",
    "Knows track, depots and manual braking.",
  ],
  [
    "Далекобійник",
    "Long-haul driver",
    "Проходить 900 км за добу будь-якими дорогами.",
    "Covers 900 km a day on any road.",
  ],
  [
    "Автомеханік",
    "Auto mechanic",
    "Перебирає двигун і переводить його на газ.",
    "Rebuilds an engine and converts it to gas.",
  ],
  [
    "Шахтар",
    "Miner",
    "Кріпить виробки, працює у тісноті й темряві.",
    "Shores tunnels, works cramped and blind.",
  ],
  [
    "Кранівник",
    "Crane operator",
    "Піднімає й точно ставить багатотонні вантажі.",
    "Lifts and places multi-ton loads precisely.",
  ],
  [
    "Пожежний-рятувальник",
    "Firefighter",
    "Гасить, ріже метал, витягує людей із завалів.",
    "Fights fire, cuts metal, pulls people from rubble.",
  ],
  [
    "Водолаз-рятувальник",
    "Rescue diver",
    "Працює під водою й у затоплених приміщеннях.",
    "Works underwater and in flooded spaces.",
  ],
  [
    "Військовий сапер",
    "Combat engineer",
    "Розміновує, будує переправи й укриття.",
    "Clears mines, builds crossings and shelters.",
  ],
  [
    "Інструктор зі стрільби",
    "Marksmanship instructor",
    "Навчає володіти зброєю та чистити її.",
    "Teaches weapon handling and maintenance.",
  ],
  [
    "Поліцейський-дільничний",
    "Community police officer",
    "Гасить конфлікти й веде розслідування.",
    "Defuses conflicts and runs an investigation.",
  ],
  [
    "Юрист",
    "Lawyer",
    "Складає правила співжиття й веде переговори.",
    "Drafts the rules of coexistence and negotiates.",
  ],
  [
    "Учитель початкових класів",
    "Primary school teacher",
    "Навчає дітей і організовує їхній день.",
    "Teaches children and structures their day.",
  ],
  [
    "Психотерапевт",
    "Psychotherapist",
    "Знімає паніку й працює з утратою.",
    "Defuses panic and works through loss.",
  ],
  [
    "Соціальний працівник",
    "Social worker",
    "Розподіляє допомогу й доглядає слабких.",
    "Distributes aid and cares for the weak.",
  ],
  [
    "Священник",
    "Priest",
    "Тримає громаду разом, ховає й мирить.",
    "Holds a community together, buries and reconciles.",
  ],
  [
    "Журналіст-розслідувач",
    "Investigative journalist",
    "Перевіряє факти й не дає керувати чутками.",
    "Checks facts and stops rumour from steering the group.",
  ],
  [
    "Актор театру",
    "Stage actor",
    "Тримає бойовий дух і вміє переконувати.",
    "Keeps morale up and knows how to persuade.",
  ],
  [
    "Музикант",
    "Musician",
    "Дає людям причину не збожеволіти від тиші.",
    "Gives people a reason not to break in the silence.",
  ],
  [
    "Бібліотекар-архівіст",
    "Archival librarian",
    "Зберігає й систематизує знання та інструкції.",
    "Preserves and indexes knowledge and manuals.",
  ],
  [
    "Бухгалтер",
    "Accountant",
    "Веде облік запасів і не дає розтягнути склад.",
    "Tracks stores and stops the pantry from vanishing.",
  ],
];

export const BIOLOGY_CARDS: readonly CardEntry[] = [
  [
    "Жінка, 24 роки",
    "Woman, 24",
    "Здорова репродуктивна система, дітей немає.",
    "Healthy reproductive system, no children.",
  ],
  [
    "Жінка, 29 років, вагітність 16 тижнів",
    "Woman, 29, 16 weeks pregnant",
    "Потребує спокою й харчування, за пів року — плюс одна людина.",
    "Needs rest and calories; in six months the group gains a person.",
  ],
  [
    "Жінка, 31 рік",
    "Woman, 31",
    "Народжувала одного разу, ускладнень не було.",
    "One prior birth, no complications.",
  ],
  [
    "Жінка, 34 роки, безплідна",
    "Woman, 34, infertile",
    "Наслідок перенесеної інфекції; в іншому здорова.",
    "Result of a past infection; otherwise healthy.",
  ],
  [
    "Жінка, 38 років",
    "Woman, 38",
    "Фертильна, але вагітність буде ризикованою.",
    "Fertile, though a pregnancy would be high-risk.",
  ],
  [
    "Жінка, 45 років",
    "Woman, 45",
    "Перименопауза, фізично міцна.",
    "Perimenopausal, physically strong.",
  ],
  [
    "Жінка, 52 роки",
    "Woman, 52",
    "Постменопауза, витривала, добре переносить холод.",
    "Postmenopausal, resilient, tolerates cold well.",
  ],
  [
    "Жінка, 63 роки",
    "Woman, 63",
    "Досвід і спокій замість фізичної сили.",
    "Experience and composure instead of physical strength.",
  ],
  [
    "Жінка, 17 років",
    "Woman, 17",
    "Ще росте, вчиться швидко, витривала.",
    "Still growing, learns fast, high stamina.",
  ],
  [
    "Жінка, 71 рік",
    "Woman, 71",
    "Потребує ліків, але зберігає ясний розум.",
    "Needs medication but stays sharp.",
  ],
  [
    "Чоловік, 19 років",
    "Man, 19",
    "Пік фізичної форми, нуль досвіду.",
    "Peak physical condition, zero experience.",
  ],
  [
    "Чоловік, 27 років",
    "Man, 27",
    "Здоровий, фертильний, добре відновлюється.",
    "Healthy, fertile, recovers quickly.",
  ],
  [
    "Чоловік, 30 років, безплідний",
    "Man, 30, infertile",
    "Підтверджено обстеженням; в іншому здоровий.",
    "Confirmed by testing; otherwise healthy.",
  ],
  [
    "Чоловік, 34 роки",
    "Man, 34",
    "Фертильний, має двох дітей поза бункером.",
    "Fertile, has two children outside the shelter.",
  ],
  [
    "Чоловік, 41 рік",
    "Man, 41",
    "Витривалий, помітно втрачає швидкість.",
    "Enduring, noticeably slower than he was.",
  ],
  [
    "Чоловік, 48 років",
    "Man, 48",
    "Фертильність знижена, сила збережена.",
    "Reduced fertility, strength intact.",
  ],
  [
    "Чоловік, 55 років",
    "Man, 55",
    "Працездатний, потребує довшого відпочинку.",
    "Fit for work, needs longer recovery.",
  ],
  [
    "Чоловік, 68 років",
    "Man, 68",
    "Фізично слабкий, але надзвичайно досвідчений.",
    "Physically weak but deeply experienced.",
  ],
  [
    "Чоловік, 16 років",
    "Man, 16",
    "Підліток, їсть багато, вчиться миттєво.",
    "A teenager who eats a lot and learns instantly.",
  ],
  [
    "Чоловік, 74 роки",
    "Man, 74",
    "Потребує догляду, безцінний як наставник.",
    "Needs care, invaluable as a mentor.",
  ],
  [
    "Інтерсексна людина, 33 роки",
    "Intersex person, 33",
    "Репродуктивний статус невизначений.",
    "Reproductive status undetermined.",
  ],
  [
    "Однояйцева близнючка, 22 роки",
    "Identical twin sister, 22",
    "Друга сестра лишилася на поверхні.",
    "The other sister stayed on the surface.",
  ],
  [
    "Однояйцевий близнюк, 44 роки",
    "Identical twin brother, 44",
    "Ідеальний донор для брата, якого тут немає.",
    "A perfect donor for a brother who is not here.",
  ],
  [
    "Зріст 152 см, вага 48 кг",
    "152 cm, 48 kg",
    "Мало їсть, пролізе у вузький лаз.",
    "Eats little, fits through a narrow crawlway.",
  ],
  [
    "Зріст 198 см, вага 104 кг",
    "198 cm, 104 kg",
    "Велика сила, велика норма харчування.",
    "Great strength, great ration.",
  ],
  [
    "Рідкісна група крові O-",
    "Rare blood type O-",
    "Універсальний донор для всієї групи.",
    "Universal donor for the whole group.",
  ],
  [
    "Група крові AB+",
    "Blood type AB+",
    "Універсальний реципієнт, донор лише для своїх.",
    "Universal recipient, donor only to a few.",
  ],
  [
    "Стійкість до холоду",
    "Cold tolerance",
    "Спокійно працює при мінус двадцяти.",
    "Works calmly at minus twenty.",
  ],
  [
    "Дальтонізм",
    "Colour blindness",
    "Не розрізняє червоне й зелене маркування.",
    "Cannot read red and green markings.",
  ],
  [
    "Повна відсутність нюху",
    "No sense of smell",
    "Не відчує ані газу, ані зіпсованої їжі.",
    "Will not smell gas or spoiled food.",
  ],
  [
    "Швидкий метаболізм",
    "Fast metabolism",
    "Витривалий, але потребує подвійної пайки.",
    "Enduring, but needs a double ration.",
  ],
  [
    "Атлетична витривалість",
    "Athletic endurance",
    "Здатний працювати фізично по 14 годин.",
    "Can do physical work for 14 hours.",
  ],
];

export const HEALTH_CARDS: readonly CardEntry[] = [
  [
    "Повністю здоровий",
    "Fully healthy",
    "Жодних хронічних діагнозів і залежностей.",
    "No chronic diagnoses, no dependencies.",
  ],
  [
    "Астма",
    "Asthma",
    "Потрібен інгалятор; пил і дим — критичні.",
    "Needs an inhaler; dust and smoke are critical.",
  ],
  [
    "Діабет 1 типу",
    "Type 1 diabetes",
    "Без інсуліну — кілька тижнів життя.",
    "Weeks to live without insulin.",
  ],
  [
    "Гіпертонія",
    "Hypertension",
    "Керована таблетками, погано зносить стрес.",
    "Managed with pills, handles stress badly.",
  ],
  [
    "Алергія на пеніцилін",
    "Penicillin allergy",
    "Половина запасу антибіотиків для нього марна.",
    "Half the antibiotic stock is useless for them.",
  ],
  [
    "Короткозорість −6",
    "Myopia −6",
    "Без окулярів практично безпорадний.",
    "Nearly helpless without glasses.",
  ],
  [
    "Часткова втрата слуху",
    "Partial hearing loss",
    "Не почує тривоги ззаду.",
    "Will not hear an alarm from behind.",
  ],
  [
    "Хронічний біль у спині",
    "Chronic back pain",
    "Не підніме нічого важчого за 15 кг.",
    "Cannot lift more than 15 kg.",
  ],
  [
    "Зрощений перелом стегна",
    "Healed femur fracture",
    "Кульгає, у холод біль посилюється.",
    "Limps; the cold makes it worse.",
  ],
  [
    "Ампутовані два пальці",
    "Two amputated fingers",
    "Дрібна моторика лівої руки обмежена.",
    "Limited fine motor control in the left hand.",
  ],
  [
    "Виразка шлунка",
    "Stomach ulcer",
    "Сувора дієта, інакше кровотеча.",
    "Strict diet or a bleed.",
  ],
  [
    "Целіакія",
    "Coeliac disease",
    "Будь-яке зерно з глютеном виводить із ладу.",
    "Any gluten grain puts them down.",
  ],
  [
    "Панічні атаки",
    "Panic attacks",
    "У замкненому просторі частішають.",
    "More frequent in enclosed spaces.",
  ],
  [
    "Депресія в ремісії",
    "Depression in remission",
    "Стабільний, доки має сон і сенс.",
    "Stable while there is sleep and purpose.",
  ],
  [
    "Хронічне безсоння",
    "Chronic insomnia",
    "Спить чотири години, ідеальний нічний вартовий.",
    "Sleeps four hours; an ideal night watch.",
  ],
  [
    "Мігрень",
    "Migraine",
    "Кілька днів на місяць непрацездатний.",
    "Out of action a few days a month.",
  ],
  [
    "Контрольована епілепсія",
    "Controlled epilepsy",
    "Без ліків напади повертаються.",
    "Seizures return without medication.",
  ],
  [
    "ВІЛ, стабільна терапія",
    "HIV, stable therapy",
    "Не заразний за терапії; запас ліків на рік.",
    "Not infectious on therapy; a year of drugs left.",
  ],
  [
    "Перенесений туберкульоз",
    "Cured tuberculosis",
    "Легені ослаблені, рецидив можливий.",
    "Weakened lungs, relapse possible.",
  ],
  [
    "Ниркова недостатність",
    "Kidney failure",
    "Потрібен діаліз двічі на тиждень.",
    "Needs dialysis twice a week.",
  ],
  [
    "Кардіостимулятор",
    "Pacemaker",
    "Батареї вистачить на сім років.",
    "The battery lasts seven more years.",
  ],
  [
    "Штучний кульшовий суглоб",
    "Hip replacement",
    "Ходить нормально, бігати не може.",
    "Walks fine, cannot run.",
  ],
  [
    "Легка гемофілія",
    "Mild haemophilia",
    "Будь-який глибокий поріз небезпечний.",
    "Any deep cut is dangerous.",
  ],
  [
    "Ревматоїдний артрит",
    "Rheumatoid arthritis",
    "Суглоби рук підводять у сирості.",
    "Hand joints fail in damp air.",
  ],
  [
    "Псоріаз",
    "Psoriasis",
    "Не заразний, але виглядає лячно.",
    "Not contagious, but it looks alarming.",
  ],
  [
    "Хронічний бронхіт",
    "Chronic bronchitis",
    "Постійний кашель, погана переносимість диму.",
    "A constant cough, poor tolerance of smoke.",
  ],
  [
    "Ослаблений імунітет",
    "Weakened immune system",
    "Перший захворіє на будь-якому спалаху.",
    "First to fall ill in any outbreak.",
  ],
  [
    "Клаустрофобія",
    "Claustrophobia",
    "У бункері працює на межі самовладання.",
    "Runs on the edge of self-control underground.",
  ],
  [
    "Морська хвороба",
    "Motion sickness",
    "Непридатний до евакуації водою.",
    "Unfit for evacuation by water.",
  ],
  [
    "Кинув курити два місяці тому",
    "Quit smoking two months ago",
    "Дратівливий, але легені відновлюються.",
    "Irritable, but the lungs are recovering.",
  ],
  [
    "Алкогольна залежність у ремісії",
    "Alcohol dependency in remission",
    "Три роки тверезості; спирт на складі — ризик.",
    "Three years sober; alcohol in storage is a risk.",
  ],
  [
    "Виснаження й недосипання",
    "Exhaustion and sleep debt",
    "Здоровий, але зараз працює на 60 відсотках.",
    "Healthy, but running at 60 per cent right now.",
  ],
];

export const HOBBY_CARDS: readonly CardEntry[] = [
  [
    "Городництво",
    "Vegetable gardening",
    "Виростить їжу навіть на ящиках під лампою.",
    "Grows food even in crates under a lamp.",
  ],
  [
    "Домашнє консервування",
    "Home canning",
    "Збереже врожай на два роки без холоду.",
    "Preserves a harvest for two years without cold.",
  ],
  [
    "Стрільба з лука",
    "Archery",
    "Тиха здобич без витрати набоїв.",
    "Silent game without spending ammunition.",
  ],
  [
    "Практична стрільба",
    "Practical shooting",
    "Впевнено володіє коротким і довгим стволом.",
    "Confident with pistol and rifle alike.",
  ],
  [
    "Скелелазіння",
    "Rock climbing",
    "Працює на висоті й на мотузці.",
    "Works at height and on rope.",
  ],
  [
    "Спелеологія",
    "Caving",
    "Орієнтується в підземеллях і тіснині.",
    "Navigates underground passages and squeezes.",
  ],
  [
    "Гірський туризм",
    "Mountain trekking",
    "Тижневі переходи з важким рюкзаком.",
    "Week-long marches under a heavy pack.",
  ],
  [
    "Виживання в дикій природі",
    "Wilderness survival",
    "Вогонь, укриття, вода з нічого.",
    "Fire, shelter and water from nothing.",
  ],
  [
    "Плавання на довгі дистанції",
    "Long-distance swimming",
    "Подолає холодну воду й врятує іншого.",
    "Crosses cold water and can save another.",
  ],
  [
    "Бокс",
    "Boxing",
    "Тримає удар і зупиняє бійку.",
    "Takes a hit and stops a brawl.",
  ],
  [
    "Йога",
    "Yoga",
    "Дихальні практики проти паніки в групі.",
    "Breathing practice against group panic.",
  ],
  [
    "Марафонський біг",
    "Marathon running",
    "Дійде по допомогу туди, куди інші не дійдуть.",
    "Will reach help where others cannot.",
  ],
  [
    "Столярство",
    "Woodworking",
    "Меблі, двері, нари з будь-якої дошки.",
    "Furniture, doors and bunks from any board.",
  ],
  [
    "Ковальство",
    "Blacksmithing",
    "Кує й гартує інструмент із брухту.",
    "Forges and tempers tools from scrap.",
  ],
  [
    "Радіоаматорство",
    "Amateur radio",
    "Зв'яжеться з іншими вцілілими.",
    "Will reach other survivors.",
  ],
  [
    "Ремонт електроніки",
    "Electronics repair",
    "Оживляє плати паяльником і схемою.",
    "Revives boards with an iron and a schematic.",
  ],
  [
    "Тривимірний друк",
    "3D printing",
    "Друкує запчастини, поки є живлення й пластик.",
    "Prints spare parts while power and plastic last.",
  ],
  [
    "Астрономія",
    "Astronomy",
    "Орієнтується за зірками без приладів.",
    "Navigates by the stars without instruments.",
  ],
  [
    "Мікологія",
    "Mycology",
    "Відрізнить їстівний гриб від смертельного.",
    "Tells an edible mushroom from a lethal one.",
  ],
  [
    "Травництво",
    "Herbalism",
    "Готує знеболювальне й антисептик із рослин.",
    "Makes painkillers and antiseptics from plants.",
  ],
  [
    "Бджільництво",
    "Beekeeping",
    "Мед, віск і природний антисептик.",
    "Honey, wax and a natural antiseptic.",
  ],
  [
    "Акваріумістика",
    "Aquarium keeping",
    "Розуміє замкнені екосистеми й фільтрацію.",
    "Understands closed ecosystems and filtration.",
  ],
  [
    "Кінологія",
    "Dog training",
    "Виховає сторожового й пошукового пса.",
    "Trains a guard and search dog.",
  ],
  [
    "Шиття",
    "Sewing",
    "Одяг, намети, ремонт спорядження.",
    "Clothing, tents and gear repair.",
  ],
  [
    "В'язання",
    "Knitting",
    "Тепла білизна з будь-якої вовни.",
    "Warm layers from any wool.",
  ],
  [
    "Кулінарія",
    "Cooking",
    "Робить сумну крупу їстівною щодня.",
    "Makes dull grain edible day after day.",
  ],
  [
    "Домашнє пивоваріння",
    "Home brewing",
    "Ферментація, спирт і дезінфекція.",
    "Fermentation, alcohol and disinfection.",
  ],
  [
    "Гончарство",
    "Pottery",
    "Посуд і тара з місцевої глини.",
    "Vessels and storage from local clay.",
  ],
  [
    "Малювання",
    "Drawing",
    "Карти, схеми, портрети для документів.",
    "Maps, diagrams and portraits for records.",
  ],
  [
    "Гра на гітарі",
    "Guitar playing",
    "Найдешевший спосіб утримати людей разом.",
    "The cheapest way to keep people together.",
  ],
  [
    "Настільні стратегії",
    "Strategy board games",
    "Планує ресурси на кілька ходів уперед.",
    "Plans resources several moves ahead.",
  ],
  [
    "Фотографія",
    "Photography",
    "Фіксує стан припасів і поранень.",
    "Documents supplies and injuries.",
  ],
];

export const BAGGAGE_CARDS: readonly CardEntry[] = [
  [
    "Аптечка з антибіотиками",
    "Medical kit with antibiotics",
    "Три повні курси широкого спектра.",
    "Three full broad-spectrum courses.",
  ],
  [
    "Набір хірургічних інструментів",
    "Surgical instrument set",
    "Стерильний, із шовним матеріалом.",
    "Sterile, with suture material.",
  ],
  [
    "Ручний генератор",
    "Hand-crank generator",
    "Дає струм для радіо й ліхтарів.",
    "Powers a radio and lamps.",
  ],
  [
    "Сонячна панель 200 Вт",
    "200 W solar panel",
    "Із контролером і кабелем.",
    "With a controller and cabling.",
  ],
  [
    "Фільтр для води",
    "Water filter",
    "Очищає 4000 літрів до заміни картриджа.",
    "4000 litres before the cartridge is spent.",
  ],
  [
    "Каністра пального, 20 л",
    "20 l fuel can",
    "Стабілізоване, зберігається два роки.",
    "Stabilised, keeps for two years.",
  ],
  [
    "Мисливська рушниця й 40 набоїв",
    "Hunting rifle and 40 rounds",
    "Калібр поширений, набої ще можна знайти.",
    "A common calibre; more rounds can be found.",
  ],
  [
    "Мачете",
    "Machete",
    "Розчищає завали й чагарник.",
    "Clears rubble and brush.",
  ],
  [
    "Багатофункціональний ніж",
    "Multi-tool knife",
    "Двадцять інструментів у кишені.",
    "Twenty tools in a pocket.",
  ],
  [
    "Сокира-колун",
    "Splitting axe",
    "Дрова, двері, ремонт зрубу.",
    "Firewood, doors, timber repair.",
  ],
  [
    "Штикова лопата",
    "Trench spade",
    "Копання, оборона, поховання.",
    "Digging, defence, burial.",
  ],
  [
    "Набір слюсарних інструментів",
    "Mechanic's tool set",
    "Ключі, головки, знімачі.",
    "Wrenches, sockets, pullers.",
  ],
  [
    "Інверторний зварювальний апарат",
    "Inverter welder",
    "Працює від генератора, з електродами.",
    "Runs off the generator, electrodes included.",
  ],
  [
    "Пара раций на 5 км",
    "Pair of 5 km radios",
    "Зв'язок для розвідувальної групи.",
    "Communications for a scouting party.",
  ],
  [
    "Короткохвильовий приймач",
    "Shortwave receiver",
    "Ловить передачі з іншого континенту.",
    "Picks up broadcasts from another continent.",
  ],
  [
    "Супутниковий телефон",
    "Satellite phone",
    "Без підписки; можливо, її ще відновлять.",
    "No subscription; it might be restored.",
  ],
  [
    "Компас і паперові карти",
    "Compass and paper maps",
    "Працюють без супутників і живлення.",
    "Work without satellites or power.",
  ],
  [
    "Насіння овочів на 200 м²",
    "Vegetable seed for 200 m²",
    "Не гібридне, можна збирати своє.",
    "Non-hybrid, you can save your own seed.",
  ],
  [
    "Мішок насіннєвої картоплі",
    "Sack of seed potatoes",
    "Перший урожай уже за 90 днів.",
    "A first harvest in 90 days.",
  ],
  [
    "Ящик м'ясних консервів",
    "Case of tinned meat",
    "Сорок банок, термін ще чотири роки.",
    "Forty tins, four years of shelf life.",
  ],
  [
    "Сіль, 10 кг",
    "10 kg of salt",
    "Консервування, гігієна, обмін.",
    "Preserving, hygiene, barter.",
  ],
  [
    "Спальник до −20 °C",
    "Sleeping bag rated −20 °C",
    "Виживання у неопалюваному приміщенні.",
    "Survival in an unheated room.",
  ],
  [
    "Двомісний намет",
    "Two-person tent",
    "Для карантину або виходу на поверхню.",
    "For quarantine or a trip outside.",
  ],
  [
    "Зимовий одяг на трьох",
    "Winter clothing for three",
    "Мембрана, фліс, чоботи.",
    "Shell, fleece and boots.",
  ],
  [
    "Гумовий човен із веслами",
    "Inflatable boat with oars",
    "Витримує чотирьох із вантажем.",
    "Carries four with cargo.",
  ],
  [
    "Велосипед із запасними камерами",
    "Bicycle with spare tubes",
    "Сто кілометрів на день без пального.",
    "A hundred kilometres a day without fuel.",
  ],
  [
    "Вівчарка, 3 роки",
    "Shepherd dog, 3 years old",
    "Навчена охороні й пошуку.",
    "Trained for guarding and search.",
  ],
  [
    "Кішка",
    "Cat",
    "Захист запасів зерна від гризунів.",
    "Protects the grain store from rodents.",
  ],
  [
    "Курка-несучка з півнем",
    "Laying hen with a rooster",
    "Яйця й можливість розводити птицю.",
    "Eggs and a chance to breed poultry.",
  ],
  [
    "Ящик горілки",
    "Case of vodka",
    "Антисептик, знеболювальне, валюта.",
    "Antiseptic, painkiller, currency.",
  ],
  [
    "Дитячі книжки й зошити",
    "Children's books and notebooks",
    "Освіта для тих, хто народиться далі.",
    "Schooling for whoever is born next.",
  ],
  [
    "Ящик мила й дезінфектора",
    "Case of soap and disinfectant",
    "Найдешевший спосіб не втратити половину групи.",
    "The cheapest way not to lose half the group.",
  ],
];

export const FACT_CARDS: readonly CardEntry[] = [
  [
    "Рік прожив у полярній експедиції",
    "Spent a year on a polar expedition",
    "Знає, як не збожеволіти в замкненій групі.",
    "Knows how not to break inside a closed group.",
  ],
  [
    "Вижив у пожежі багатоповерхівки",
    "Survived a high-rise fire",
    "Опіки на спині, страху вогню немає.",
    "Burns on the back, no fear of fire.",
  ],
  [
    "Служив у миротворчому контингенті",
    "Served with a peacekeeping force",
    "Бачив розподіл ресурсів у таборах.",
    "Has seen how camps ration supplies.",
  ],
  [
    "Три роки керував волонтерським штабом",
    "Ran a volunteer hub for three years",
    "Логістика, люди, конфлікти.",
    "Logistics, people, conflicts.",
  ],
  [
    "Має судимість за шахрайство",
    "Convicted of fraud",
    "Відсидів два роки, борг не повернув.",
    "Served two years, never repaid the debt.",
  ],
  [
    "Провів три місяці в полоні",
    "Held captive for three months",
    "Витримає тиск, не довіряє нікому швидко.",
    "Withstands pressure, trusts nobody quickly.",
  ],
  [
    "Не вміє плавати",
    "Cannot swim",
    "Уникає води й не зізнається в цьому.",
    "Avoids water and will not admit it.",
  ],
  [
    "Панічно боїться темряви",
    "Terrified of darkness",
    "Без світла не працює й не спить.",
    "Will not work or sleep without light.",
  ],
  [
    "Володіє чотирма мовами",
    "Speaks four languages",
    "Перекладе будь-які знайдені інструкції.",
    "Will translate any manual you find.",
  ],
  [
    "Знає жестову мову",
    "Knows sign language",
    "Зв'язок у тиші й при пошкодженому слуху.",
    "Communication in silence or with damaged hearing.",
  ],
  [
    "Приймав пологи двічі",
    "Delivered two babies",
    "Обидва рази поза лікарнею.",
    "Both times outside a hospital.",
  ],
  [
    "Ніколи не виїжджав за межі області",
    "Never left their home region",
    "Не знає нічого за 200 км звідси.",
    "Knows nothing beyond 200 km from here.",
  ],
  [
    "Виріс у селі",
    "Grew up in a village",
    "Доїть корову, коле дрова, ріже птицю.",
    "Milks a cow, splits wood, slaughters poultry.",
  ],
  [
    "Пройшов курс тактичної медицини",
    "Completed a tactical medicine course",
    "Джгут, декомпресія, евакуація.",
    "Tourniquet, decompression, evacuation.",
  ],
  [
    "Має ліцензію пілота-любителя",
    "Holds a private pilot licence",
    "Підніме легкий літак, якщо той знайдеться.",
    "Will fly a light aircraft if one turns up.",
  ],
  [
    "Керує вантажівкою й трактором",
    "Drives trucks and tractors",
    "Категорії відкриті, практика свіжа.",
    "Licensed and recently practised.",
  ],
  [
    "Був інструктором з виживання",
    "Worked as a survival instructor",
    "Навчав групи по 20 осіб у лісі.",
    "Taught groups of 20 in the field.",
  ],
  [
    "Вирощує гриби у підвалі",
    "Grows mushrooms in a cellar",
    "Білок без сонця й ґрунту.",
    "Protein without sun or soil.",
  ],
  [
    "Читає й ремонтує старі схеми",
    "Reads and repairs legacy circuits",
    "Радянська й аналогова техніка — його.",
    "Analogue and Soviet-era gear is their domain.",
  ],
  [
    "Пам'ятає напам'ять 300 рецептів",
    "Knows 300 recipes by heart",
    "Куховарить без книжки з чого завгодно.",
    "Cooks anything without a book.",
  ],
  [
    "Тричі банкрутував",
    "Went bankrupt three times",
    "Ризикує охоче й програє часто.",
    "Takes risks readily and loses often.",
  ],
  [
    "Виграв суд проти корпорації",
    "Won a case against a corporation",
    "Уміє тиснути й не відступати.",
    "Knows how to push and not back down.",
  ],
  [
    "Керував командою з 40 людей",
    "Managed a team of 40",
    "Розподіляє роботу без криків.",
    "Assigns work without shouting.",
  ],
  [
    "Ніколи не тримав зброї",
    "Never held a weapon",
    "Категорично відмовляється вчитися.",
    "Flatly refuses to learn.",
  ],
  [
    "Уміє шити взуття",
    "Can make shoes",
    "З ременів і покришок за один день.",
    "From belts and tyres in a single day.",
  ],
  [
    "Розводив рибу у ставку",
    "Farmed fish in a pond",
    "Знає, як годувати й не отруїти воду.",
    "Knows how to feed stock without poisoning water.",
  ],
  [
    "Веде щоденник двадцять років",
    "Has kept a diary for twenty years",
    "Записує все, помічає закономірності.",
    "Records everything and spots patterns.",
  ],
  [
    "Мав власну ферму",
    "Owned a farm",
    "Втратив її через борги минулого року.",
    "Lost it to debt last year.",
  ],
  [
    "Три роки жив без електрики",
    "Lived three years without electricity",
    "Побут при свічках його не лякає.",
    "Life by candlelight does not frighten them.",
  ],
  [
    "Сам виховує двох дітей",
    "Raising two children alone",
    "Обоє лишилися нагорі.",
    "Both stayed on the surface.",
  ],
  [
    "Доглядає літню матір",
    "Cares for an elderly mother",
    "Не піде нікуди без неї.",
    "Will go nowhere without her.",
  ],
  [
    "Постійно конфліктує з керівництвом",
    "Constantly clashes with authority",
    "Звільнявся з чотирьох робіт за рік.",
    "Left four jobs in a year.",
  ],
  [
    "Засинає будь-де за дві хвилини",
    "Falls asleep anywhere in two minutes",
    "Відновлюється швидше за всіх.",
    "Recovers faster than anyone.",
  ],
  [
    "Не переносить самотності",
    "Cannot bear solitude",
    "Наодинці працює вдвічі гірше.",
    "Works half as well alone.",
  ],
  [
    "Схильний привласнювати дрібниці",
    "Prone to petty pilfering",
    "Дрібно, постійно, без злого наміру.",
    "Small, constant, without real malice.",
  ],
  [
    "Категорично проти насильства",
    "Categorically against violence",
    "Не візьме зброю навіть для оборони.",
    "Will not take up arms even in defence.",
  ],
  [
    "Тримає слово собі на шкоду",
    "Keeps their word to their own cost",
    "Обіцянка для нього вагоміша за вигоду.",
    "A promise outweighs advantage.",
  ],
  [
    "Домовиться з ким завгодно",
    "Can negotiate with anyone",
    "Виторгував воду в озброєної групи.",
    "Talked water out of an armed group.",
  ],
  [
    "Швидко панікує в натовпі",
    "Panics quickly in a crowd",
    "У тисняві стає некерованим.",
    "Becomes uncontrollable in a crush.",
  ],
  [
    "Був рятувальником-добровольцем",
    "Volunteered with a rescue service",
    "Шість років виїздів на завали.",
    "Six years of callouts to collapses.",
  ],
  [
    "Знає основи ветеринарії",
    "Knows basic veterinary care",
    "Виходив теля й зашивав собаку.",
    "Saved a calf and stitched a dog.",
  ],
  [
    "Точить і ремонтує інструмент",
    "Sharpens and repairs tools",
    "Продовжує життя всьому залізу вдвічі.",
    "Doubles the life of every blade.",
  ],
  [
    "Здатний тиждень працювати майже без сну",
    "Can work a week on almost no sleep",
    "Потім вимикається на добу.",
    "Then sleeps for a full day.",
  ],
  [
    "Не вживає алкоголю взагалі",
    "Does not drink at all",
    "Спокійно охоронятиме склад зі спиртом.",
    "Can be trusted to guard the alcohol.",
  ],
  [
    "Легко знаходить мову з дітьми",
    "Connects with children easily",
    "Заспокоїть будь-яку дитину за хвилину.",
    "Calms any child in a minute.",
  ],
  [
    "Був наставником у школі",
    "Mentored at a school",
    "Уміє передавати знання, а не лише мати їх.",
    "Can pass knowledge on, not just hold it.",
  ],
  [
    "Пережив клінічну смерть",
    "Survived clinical death",
    "Чотири хвилини без пульсу; наслідків немає.",
    "Four minutes without a pulse; no lasting damage.",
  ],
  [
    "Орієнтується за зірками",
    "Navigates by the stars",
    "Виведе групу вночі без приладів.",
    "Will lead a group at night without instruments.",
  ],
  [
    "Пробіг ультрамарафон 100 км",
    "Ran a 100 km ultramarathon",
    "Витривалість вище за будь-кого в кімнаті.",
    "More endurance than anyone in the room.",
  ],
  [
    "Приховує, що вже був у цьому бункері",
    "Hides having been in this shelter before",
    "Знає планування й другий вихід.",
    "Knows the layout and the second exit.",
  ],
];

export type SpecialConditionCard = Readonly<{
  title: readonly [uk: string, en: string];
  details: readonly [uk: string, en: string];
  timing: string;
  effect: Readonly<Record<string, unknown>>;
}>;

const special = (
  titleUk: string,
  titleEn: string,
  detailUk: string,
  detailEn: string,
  timing: string,
  effect: Readonly<Record<string, unknown>>,
): SpecialConditionCard => ({
  title: [titleUk, titleEn],
  details: [detailUk, detailEn],
  timing,
  effect,
});

export const SPECIAL_CONDITION_CARDS: readonly SpecialConditionCard[] = [
  special(
    "Друге захоплення",
    "Second calling",
    "Оберіть гравця: його Хобі замінюють новою картою з колоди.",
    "Choose a player: their Hobby is replaced with a fresh card.",
    "discussion",
    { type: "swap-card", category: "hobby" },
  ),
  special(
    "Перекваліфікація",
    "Retraining",
    "Оберіть гравця: його Професію замінюють новою картою.",
    "Choose a player: their Profession is replaced with a fresh card.",
    "discussion",
    { type: "swap-card", category: "profession" },
  ),
  special(
    "Медогляд",
    "Medical review",
    "Оберіть гравця: його Здоров'я замінюють новою картою.",
    "Choose a player: their Health is replaced with a fresh card.",
    "discussion",
    { type: "swap-card", category: "health" },
  ),
  special(
    "Перепакування",
    "Repacking",
    "Оберіть гравця: його Багаж замінюють новою картою.",
    "Choose a player: their Baggage is replaced with a fresh card.",
    "discussion",
    { type: "swap-card", category: "baggage" },
  ),
  special(
    "Нова біографія",
    "New biography",
    "Оберіть гравця: його Факт замінюють новою картою.",
    "Choose a player: their Fact is replaced with a fresh card.",
    "discussion",
    { type: "swap-card", category: "fact" },
  ),
  special(
    "Повторний аналіз",
    "Repeat analysis",
    "Оберіть гравця: його Біологію замінюють новою картою.",
    "Choose a player: their Biology is replaced with a fresh card.",
    "discussion",
    { type: "swap-card", category: "biology" },
  ),
  special(
    "Обмовка",
    "Slip of the tongue",
    "Відкрийте одну свою випадкову приховану характеристику.",
    "Reveal one random hidden trait of your own.",
    "reveal",
    { type: "reveal-random", count: 1 },
  ),
  special(
    "Прорив паніки",
    "Panic breach",
    "Відкрийте дві свої випадкові приховані характеристики.",
    "Reveal two random hidden traits of your own.",
    "reveal",
    { type: "reveal-random", count: 2 },
  ),
  special(
    "Нічна сповідь",
    "Night confession",
    "Відкрийте одну випадкову приховану характеристику.",
    "Reveal one random hidden trait.",
    "reveal",
    { type: "reveal-random", count: 1 },
  ),
  special(
    "Сон під запис",
    "Talking in your sleep",
    "Відкрийте одну випадкову приховану характеристику.",
    "Reveal one random hidden trait.",
    "reveal",
    { type: "reveal-random", count: 1 },
  ),
  special(
    "Гарячка",
    "Fever",
    "Відкрийте дві свої випадкові приховані характеристики.",
    "Reveal two of your random hidden traits.",
    "reveal",
    { type: "reveal-random", count: 2 },
  ),
  special(
    "Незамінний",
    "Indispensable",
    "Цього голосування вас не можна вигнати.",
    "You cannot be exiled in this vote.",
    "before-vote",
    { type: "protect-from-vote", rounds: 1 },
  ),
  special(
    "Пільга старожила",
    "Old-timer's exemption",
    "Цього голосування вас не можна вигнати.",
    "You cannot be exiled in this vote.",
    "before-vote",
    { type: "protect-from-vote", rounds: 1 },
  ),
  special(
    "Ключ від складу",
    "Keys to the store",
    "Цього голосування вас не можна вигнати.",
    "You cannot be exiled in this vote.",
    "before-vote",
    { type: "protect-from-vote", rounds: 1 },
  ),
  special(
    "Єдиний донор",
    "The only donor",
    "Цього голосування вас не можна вигнати.",
    "You cannot be exiled in this vote.",
    "before-vote",
    { type: "protect-from-vote", rounds: 1 },
  ),
  special(
    "Карантин",
    "Quarantine",
    "Цього голосування вас не можна вигнати.",
    "You cannot be exiled in this vote.",
    "before-vote",
    { type: "protect-from-vote", rounds: 1 },
  ),
  special(
    "Право коменданта",
    "Warden's prerogative",
    "Цього голосування ваш голос рахується двічі.",
    "Your ballot counts twice in this vote.",
    "before-vote",
    { type: "double-vote", rounds: 1 },
  ),
  special(
    "Голос більшості",
    "Voice of the majority",
    "Цього голосування ваш голос рахується двічі.",
    "Your ballot counts twice in this vote.",
    "before-vote",
    { type: "double-vote", rounds: 1 },
  ),
  special(
    "Довіра громади",
    "Community trust",
    "Цього голосування ваш голос рахується двічі.",
    "Your ballot counts twice in this vote.",
    "before-vote",
    { type: "double-vote", rounds: 1 },
  ),
  special(
    "Останнє слово",
    "The last word",
    "Цього голосування ваш голос рахується двічі.",
    "Your ballot counts twice in this vote.",
    "before-vote",
    { type: "double-vote", rounds: 1 },
  ),
  special(
    "Старший зміни",
    "Shift supervisor",
    "Цього голосування ваш голос рахується двічі.",
    "Your ballot counts twice in this vote.",
    "before-vote",
    { type: "double-vote", rounds: 1 },
  ),
  special(
    "Допит",
    "Interrogation",
    "Оберіть гравця: він відкриває одну приховану характеристику на вибір.",
    "Choose a player: they reveal one hidden trait of their choice.",
    "discussion",
    { type: "force-reveal" },
  ),
  special(
    "Перевірка документів",
    "Papers, please",
    "Оберіть гравця: він відкриває свою Професію.",
    "Choose a player: they reveal their Profession.",
    "discussion",
    { type: "force-reveal", category: "profession" },
  ),
  special(
    "Обшук речей",
    "Bag search",
    "Оберіть гравця: він відкриває свій Багаж.",
    "Choose a player: they reveal their Baggage.",
    "discussion",
    { type: "force-reveal", category: "baggage" },
  ),
  special(
    "Медична комісія",
    "Medical board",
    "Оберіть гравця: він відкриває своє Здоров'я.",
    "Choose a player: they reveal their Health.",
    "discussion",
    { type: "force-reveal", category: "health" },
  ),
  special(
    "Особова справа",
    "Personnel file",
    "Оберіть гравця: він відкриває свій Факт.",
    "Choose a player: they reveal their Fact.",
    "discussion",
    { type: "force-reveal", category: "fact" },
  ),
  special(
    "Анкета переселенця",
    "Resettlement form",
    "Оберіть гравця: він відкриває свою Біологію.",
    "Choose a player: they reveal their Biology.",
    "discussion",
    { type: "force-reveal", category: "biology" },
  ),
  special(
    "Розмова до відбою",
    "Talk before lights out",
    "Оберіть гравця: він відкриває своє Хобі.",
    "Choose a player: they reveal their Hobby.",
    "discussion",
    { type: "force-reveal", category: "hobby" },
  ),
  special(
    "Помилка в списках",
    "Clerical error",
    "Оберіть гравця: ви міняєтеся з ним персонажами.",
    "Choose a player: you swap characters with them.",
    "before-game",
    { type: "exchange-characters" },
  ),
  special(
    "Підміна на вході",
    "Swapped at the door",
    "Оберіть гравця: ви міняєтеся з ним персонажами.",
    "Choose a player: you swap characters with them.",
    "before-game",
    { type: "exchange-characters" },
  ),
  special(
    "Двійник",
    "The double",
    "Оберіть гравця: ви міняєтеся з ним персонажами.",
    "Choose a player: you swap characters with them.",
    "before-game",
    { type: "exchange-characters" },
  ),
  special(
    "Чужий квиток",
    "Someone else's ticket",
    "Оберіть гравця: ви міняєтеся з ним персонажами.",
    "Choose a player: you swap characters with them.",
    "before-game",
    { type: "exchange-characters" },
  ),
];

export type ContextCard = Readonly<{
  title: readonly [uk: string, en: string];
  consequence: readonly [uk: string, en: string];
  usefulTags: readonly string[];
}>;

const context = (
  titleUk: string,
  titleEn: string,
  consequenceUk: string,
  consequenceEn: string,
  ...usefulTags: string[]
): ContextCard => ({
  title: [titleUk, titleEn],
  consequence: [consequenceUk, consequenceEn],
  usefulTags,
});

export const CATASTROPHE_CARDS: readonly ContextCard[] = [
  context(
    "Обмін ядерними ударами",
    "Nuclear exchange",
    "Поверхня радіоактивна щонайменше 12 років; вихід тільки в захисті.",
    "The surface stays radioactive for at least 12 years; no trips without protection.",
    "radiation",
    "medicine",
    "engineering",
  ),
  context(
    "Пандемія повітряного вірусу",
    "Airborne pandemic",
    "Смертність 60 відсотків; будь-який новоприбулий — ризик для всіх.",
    "60 per cent lethality; any newcomer risks everyone.",
    "medicine",
    "sanitation",
    "quarantine",
  ),
  context(
    "Удар астероїда",
    "Asteroid impact",
    "Пил закрив сонце; п'ять років без урожаю на поверхні.",
    "Dust blocks the sun; five years without a surface harvest.",
    "food",
    "farming",
    "light",
  ),
  context(
    "Наднова сонячна буря",
    "Extreme solar storm",
    "Уся електроніка без екранування згоріла.",
    "All unshielded electronics are burned out.",
    "engineering",
    "radio",
    "power",
  ),
  context(
    "Виверження супервулкана",
    "Supervolcano eruption",
    "Попіл, кислотні дощі, зима на десятиліття.",
    "Ash, acid rain and a decade-long winter.",
    "farming",
    "filtration",
    "warmth",
  ),
  context(
    "Глобальна повінь",
    "Global flooding",
    "Рівень води піднявся на 40 метрів; суша фрагментована.",
    "Water rose 40 metres; land is fragmented.",
    "water",
    "boats",
    "fishing",
  ),
  context(
    "Витік бойового штаму",
    "Engineered pathogen leak",
    "Збудник живе у ґрунті роками; будь-яка рана смертельна.",
    "The agent survives in soil for years; any wound is lethal.",
    "medicine",
    "sanitation",
    "protection",
  ),
  context(
    "Колапс магнітного поля",
    "Magnetic field collapse",
    "Космічне випромінювання зростає; денна поверхня небезпечна.",
    "Cosmic radiation rises; daylight on the surface is dangerous.",
    "radiation",
    "shelter",
    "night-work",
  ),
  context(
    "Тотальна посуха",
    "Total drought",
    "Прісна вода лише з підземних горизонтів.",
    "Fresh water comes only from underground aquifers.",
    "water",
    "drilling",
    "filtration",
  ),
  context(
    "Нашестя комах-шкідників",
    "Insect plague",
    "Знищено всі посіви й запаси зерна на поверхні.",
    "Every surface crop and grain store is destroyed.",
    "food",
    "chemistry",
    "sealed-storage",
  ),
  context(
    "Ядерна зима",
    "Nuclear winter",
    "Мінус 30 влітку; паливо важливіше за їжу.",
    "Minus 30 in summer; fuel matters more than food.",
    "warmth",
    "fuel",
    "clothing",
  ),
  context(
    "Аварія на АЕС поруч",
    "Nearby reactor meltdown",
    "Зона відчуження 50 км; вода й ґрунт заражені.",
    "A 50 km exclusion zone; water and soil are contaminated.",
    "radiation",
    "water",
    "medicine",
  ),
  context(
    "Хімічна атака",
    "Chemical attack",
    "Отрута осіла в низинах і триматиметься місяцями.",
    "The agent settled in low ground and will linger for months.",
    "protection",
    "chemistry",
    "ventilation",
  ),
  context(
    "Колапс енергосистем",
    "Grid collapse",
    "Централізованого струму немає ніде на континенті.",
    "No central power anywhere on the continent.",
    "power",
    "engineering",
    "fuel",
  ),
  context(
    "Повний крах держав",
    "Total state collapse",
    "Закону немає; озброєні групи ділять території.",
    "No law; armed groups divide the territory.",
    "defence",
    "negotiation",
    "medicine",
  ),
  context(
    "Стійкість до всіх антибіотиків",
    "Total antibiotic resistance",
    "Звичайна подряпина знову вбиває.",
    "An ordinary scratch kills again.",
    "medicine",
    "sanitation",
    "herbalism",
  ),
  context(
    "Втрата запилювачів",
    "Pollinator collapse",
    "Більшість культур не плодоносить без ручного запилення.",
    "Most crops fail without hand pollination.",
    "farming",
    "beekeeping",
    "food",
  ),
  context(
    "Некерований штучний інтелект",
    "Runaway artificial intelligence",
    "Будь-яка підключена система ворожа; надійне лише аналогове.",
    "Any connected system is hostile; only analogue is safe.",
    "analogue",
    "engineering",
    "navigation",
  ),
  context(
    "Океанічна аноксія",
    "Ocean anoxia",
    "Морська їжа отруйна; узбережжя непридатне.",
    "Sea food is toxic; the coast is uninhabitable.",
    "food",
    "farming",
    "medicine",
  ),
  context(
    "Тривала темрява",
    "Prolonged darkness",
    "Сонячне світло не доходить до поверхні 18 місяців.",
    "Sunlight will not reach the ground for 18 months.",
    "light",
    "power",
    "mental-health",
  ),
];

export const BUNKER_CARDS: readonly ContextCard[] = [
  context(
    "Дизельний генератор і 800 л пального",
    "Diesel generator with 800 l of fuel",
    "Повне живлення на чотири місяці безперервно.",
    "Full power for four months of continuous use.",
    "power",
    "fuel",
  ),
  context(
    "Артезіанська свердловина",
    "Artesian well",
    "Необмежена питна вода, потрібен насос.",
    "Unlimited drinking water; a pump is required.",
    "water",
  ),
  context(
    "Система регенерації повітря",
    "Air regeneration system",
    "Замкнений цикл на 12 осіб, фільтри на два роки.",
    "A closed cycle for 12 people, filters for two years.",
    "air",
    "filtration",
  ),
  context(
    "Склад консервів на два роки",
    "Two years of tinned food",
    "Розрахунок на вісьмох; на дванадцятьох — 16 місяців.",
    "Rationed for eight; for twelve it lasts 16 months.",
    "food",
  ),
  context(
    "Гідропонна теплиця",
    "Hydroponic greenhouse",
    "40 м² під лампами, потребує багато струму.",
    "40 m² under lamps, power hungry.",
    "food",
    "farming",
    "power",
  ),
  context(
    "Медичний блок з операційною",
    "Medical bay with an operating room",
    "Стерильна зона, наркоз, рентген.",
    "A sterile zone, anaesthesia and an x-ray unit.",
    "medicine",
  ),
  context(
    "Аптека повного циклу",
    "Full pharmacy",
    "Антибіотики, знеболювальні, інсулін на рік.",
    "Antibiotics, painkillers and a year of insulin.",
    "medicine",
  ),
  context(
    "Майстерня з верстатами",
    "Machine shop",
    "Токарний, свердлильний, зварювання.",
    "Lathe, drill press and welding.",
    "engineering",
    "tools",
  ),
  context(
    "Склад інструменту й кріплення",
    "Tool and fastener store",
    "Усе для ремонту конструкцій.",
    "Everything needed to repair the structure.",
    "tools",
    "engineering",
  ),
  context(
    "Бібліотека технічних довідників",
    "Library of technical manuals",
    "Паперові інструкції з медицини, агро й механіки.",
    "Paper manuals on medicine, agriculture and mechanics.",
    "knowledge",
  ),
  context(
    "Радіовузол з антеною на поверхні",
    "Radio room with a surface antenna",
    "Прийом і передача на сотні кілометрів.",
    "Receives and transmits over hundreds of kilometres.",
    "radio",
    "navigation",
  ),
  context(
    "Сонячна станція 6 кВт",
    "6 kW solar array",
    "Живлення без пального, поки є світло.",
    "Fuel-free power while there is daylight.",
    "power",
  ),
  context(
    "Резервуар на 30 тонн води",
    "30-tonne water tank",
    "Запас на пів року при жорсткому ліміті.",
    "Half a year at a strict ration.",
    "water",
  ),
  context(
    "Очисні споруди",
    "Sewage treatment",
    "Замкнена санітарія без виходу назовні.",
    "Closed sanitation with no trips outside.",
    "sanitation",
  ),
  context(
    "Насіннєве сховище",
    "Seed vault",
    "Понад 200 сортів, зберігання на 20 років.",
    "Over 200 varieties, viable for 20 years.",
    "farming",
    "food",
  ),
  context(
    "Морозильна камера",
    "Freezer chamber",
    "Довге зберігання м'яса й вакцин.",
    "Long-term storage for meat and vaccines.",
    "food",
    "medicine",
    "power",
  ),
  context(
    "Оружейна кімната",
    "Armoury",
    "Чотири стволи й 600 набоїв.",
    "Four firearms and 600 rounds.",
    "defence",
  ),
  context(
    "Гермодвері з ручним приводом",
    "Manual pressure door",
    "Тримає тиск і не залежить від струму.",
    "Holds pressure and needs no power.",
    "defence",
    "engineering",
  ),
  context(
    "Дозиметри й захисні костюми",
    "Dosimeters and protective suits",
    "Шість комплектів для виходу на поверхню.",
    "Six sets for trips to the surface.",
    "radiation",
    "protection",
  ),
  context(
    "Запасний вихід за 400 метрів",
    "Emergency exit 400 metres away",
    "Виводить у лісосмугу поза периметром.",
    "Comes out in a treeline beyond the perimeter.",
    "escape",
    "defence",
  ),
  context(
    "Автономне опалення на дровах",
    "Wood-fired heating",
    "Працює без електрики, потрібен запас дров.",
    "Runs without electricity; needs a wood supply.",
    "warmth",
    "fuel",
  ),
  context(
    "Каналізаційний колектор поруч",
    "Sewer main nearby",
    "Прихований шлях у місто на два кілометри.",
    "A hidden two-kilometre route into the city.",
    "escape",
    "scouting",
  ),
  context(
    "Ферма личинок і грибів",
    "Insect and mushroom farm",
    "Білок без сонця й майже без води.",
    "Protein without sun and almost without water.",
    "food",
  ),
  context(
    "Пральня й душові",
    "Laundry and showers",
    "Гігієна для 12 осіб щотижня.",
    "Hygiene for 12 people every week.",
    "sanitation",
  ),
  context(
    "Кімната карантину",
    "Quarantine room",
    "Ізоляція на двох із окремою вентиляцією.",
    "Isolation for two with separate ventilation.",
    "medicine",
    "quarantine",
  ),
  context(
    "Спортзал",
    "Gym",
    "Фізична форма й скид напруги.",
    "Fitness and a release for tension.",
    "mental-health",
  ),
  context(
    "Дитяча кімната й шкільні матеріали",
    "Nursery and school supplies",
    "Розраховано на трьох дітей.",
    "Set up for three children.",
    "children",
    "knowledge",
  ),
  context(
    "Архів документів і карт району",
    "Archive of local maps and records",
    "Комунікації, укриття, склади в радіусі 50 км.",
    "Utilities, shelters and depots within 50 km.",
    "knowledge",
    "navigation",
  ),
  context(
    "Гараж із позашляховиком",
    "Garage with an off-road vehicle",
    "Повний бак і комплект запчастин.",
    "A full tank and a spare parts kit.",
    "transport",
    "fuel",
  ),
  context(
    "Запас палива на 5 років",
    "Five-year fuel reserve",
    "Стабілізоване дизельне, 6000 літрів.",
    "Stabilised diesel, 6000 litres.",
    "fuel",
    "power",
  ),
];

export const THREAT_CARDS: readonly ContextCard[] = [
  context(
    "Відмова вентиляції",
    "Ventilation failure",
    "Дві доби до отруєння вуглекислим газом.",
    "Two days before carbon dioxide poisoning.",
    "engineering",
    "tools",
    "air",
  ),
  context(
    "Прорив ґрунтових вод",
    "Groundwater breach",
    "Затоплює нижній рівень зі швидкістю 3 см на годину.",
    "The lower level floods at 3 cm an hour.",
    "engineering",
    "pumps",
    "construction",
  ),
  context(
    "Пожежа в технічному відсіку",
    "Fire in the plant room",
    "Дим іде по всій вентиляції.",
    "Smoke spreads through the whole ventilation system.",
    "firefighting",
    "medicine",
    "engineering",
  ),
  context(
    "Спалах кишкової інфекції",
    "Gastrointestinal outbreak",
    "Половина групи зневоднена за три дні.",
    "Half the group is dehydrated within three days.",
    "medicine",
    "sanitation",
    "water",
  ),
  context(
    "Зіпсувався запас їжі",
    "Food stores spoiled",
    "Третина консервів здулася й непридатна.",
    "A third of the tins have swollen and are unusable.",
    "food",
    "farming",
    "hunting",
  ),
  context(
    "Вихід з ладу генератора",
    "Generator breakdown",
    "Без ремонту — темрява й мінусова температура.",
    "Without a repair: darkness and freezing.",
    "engineering",
    "power",
    "tools",
  ),
  context(
    "Озброєна група на поверхні",
    "Armed group on the surface",
    "Двадцять людей шукають вхід третій день.",
    "Twenty people have been probing for the entrance for three days.",
    "defence",
    "negotiation",
    "escape",
  ),
  context(
    "Обвал у головному коридорі",
    "Collapse in the main corridor",
    "Відрізано склад і запасний вихід.",
    "The store and the emergency exit are cut off.",
    "construction",
    "tools",
    "rescue",
  ),
  context(
    "Зараження питної води",
    "Drinking water contamination",
    "Джерело отруєне важкими металами.",
    "The source is poisoned with heavy metals.",
    "water",
    "filtration",
    "chemistry",
  ),
  context(
    "Гризуни у сховищі",
    "Rodents in the store",
    "З'їдають і псують зерно швидше, ніж ви їсте.",
    "They eat and foul grain faster than you can.",
    "food",
    "animals",
    "sanitation",
  ),
  context(
    "Відмова опалення взимку",
    "Heating failure in winter",
    "Температура падає до нуля за добу.",
    "The temperature drops to zero within a day.",
    "warmth",
    "fuel",
    "engineering",
  ),
  context(
    "Радіоактивний пил у фільтрах",
    "Radioactive dust in the filters",
    "Фільтри треба замінити, не відкриваючи контур.",
    "Filters must be changed without opening the loop.",
    "radiation",
    "protection",
    "engineering",
  ),
  context(
    "Тяжка травма з кровотечею",
    "Severe traumatic bleeding",
    "Без операції людина не доживе до ранку.",
    "Without surgery they will not see morning.",
    "medicine",
    "surgery",
    "blood",
  ),
  context(
    "Пологи з ускладненням",
    "Complicated childbirth",
    "Потрібні руки, світло й стерильність просто зараз.",
    "Hands, light and sterility are needed right now.",
    "medicine",
    "midwifery",
    "light",
  ),
  context(
    "Бунт через розподіл пайків",
    "Riot over rations",
    "Двоє вимагають переділу й погрожують ножем.",
    "Two people demand a redistribution and show a knife.",
    "negotiation",
    "defence",
    "leadership",
  ),
  context(
    "Втрата зв'язку й повна ізоляція",
    "Loss of contact and total isolation",
    "Радіо мовчить восьмий тиждень.",
    "The radio has been silent for eight weeks.",
    "radio",
    "mental-health",
    "navigation",
  ),
  context(
    "Заклинило гермодвері",
    "Pressure door jammed",
    "Ні вийти, ні впустити тих, хто зовні.",
    "Nobody can leave, and nobody outside can be let in.",
    "engineering",
    "welding",
    "tools",
  ),
  context(
    "Плісень у житловому блоці",
    "Mould in the living quarters",
    "Дихальні шляхи вражені в третини людей.",
    "A third of the group has airway symptoms.",
    "sanitation",
    "medicine",
    "chemistry",
  ),
  context(
    "Закінчилися ліки",
    "Medicines ran out",
    "Двоє хронічних хворих без терапії.",
    "Two chronic patients are without treatment.",
    "medicine",
    "herbalism",
    "scavenging",
  ),
  context(
    "Здичавіла зграя біля виходу",
    "Feral pack at the exit",
    "Виходити поодинці неможливо.",
    "Nobody can go out alone.",
    "defence",
    "animals",
    "hunting",
  ),
  context(
    "Зневіра й відмова працювати",
    "Despair and refusal to work",
    "Троє не встають третій день поспіль.",
    "Three people have not got up for three days.",
    "mental-health",
    "leadership",
    "food",
  ),
];
